/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Config.Conexion;
import Entidad.clsEAdoptante;

import Entidad.clsEEvidencia;
import Entidad.clsEFormularioAdopcion;
import Entidad.clsEVoluntario;
import Negocio.clsNAdoptante;

import Negocio.clsNFormularioAdopcion;
import Negocio.clsNVoluntario;
import java.awt.Color;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author zouoz
 */
public class FrmFormulario extends javax.swing.JFrame {

    /**
     * Creates new form FrmFormulario
     */
    private int idadoptante;
    //public String DniIngresante;
    public FrmFormulario() {
        initComponents();
        cargarDatosComboBox();
        mostrarFechaActual();
        getContentPane().setBackground(Color.WHITE); //no borren
       
    }
 

    
    //es necesairo llamar a esta funciona para obtener el valor de id adoptante
    public void ObtenerIdAdoptante() {
        clsNAdoptante objNA = new clsNAdoptante();
        String idAdoptante = objNA.obtenerIdAdoptante();
        idadoptante = Integer.parseInt(idAdoptante);
        //System.out.println("El valor de idadoptante es: " + this.idadoptante);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPregunta1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPregunta3 = new javax.swing.JTextField();
        txtPregunta2 = new javax.swing.JTextField();
        txtPregunta4 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtPregunta5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbEvidencia = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("PREGUNTA 1 : ¿Ha tenido mascotas anteriormente?");

        jLabel3.setText("PREGUNTA 2 : ¿Tienes experiencia previa en el cuidado de animales?");

        jLabel4.setText("PREGUNTA 3 : ¿Cuánto tiempo pasarías en casa con la mascota diariamente?");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel5.setText("PREGUNTA 4 : ¿Por qué estás interesado en adoptar una mascota en este momento?");

        jLabel6.setText("PREGUNTA 5 : ¿Tienes planes de mudarte en el futuro cercano?");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Fecha");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Formulario de Adopción      ");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aprobado", "pendiente", "rechazado" }));

        cmbEvidencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Estado");

        jLabel9.setText("Visita Domiciliaria");

        jLabel10.setText(" ¿Cómo planeas garantizar que la mascota pueda acompañarte en la mudanza y adaptarse al nuevo entorno?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(txtPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(180, 180, 180)
                                    .addComponent(txtPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(txtPregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(txtPregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(41, 41, 41)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)
                                .addComponent(cmbEvidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtPregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEvidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(49, 49, 49)
                .addComponent(btnGuardar)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     
          clsEFormularioAdopcion objFo = new clsEFormularioAdopcion();
          clsNFormularioAdopcion objNFo = new clsNFormularioAdopcion();
          clsEAdoptante objAdop = new clsEAdoptante();
          clsEEvidencia objEVI = new clsEEvidencia();
        
        
        //Fecha
        objFo.setFecha(LocalDate.parse(txtFecha.getText()));
                
        //Preguntas
        String p1 = txtPregunta1.getText();
        String p2 = txtPregunta2.getText();
        String p3 = txtPregunta3.getText();
        String p4 = txtPregunta4.getText();
        String p5 = txtPregunta5.getText();
        
        objFo.setP1(p1);
        objFo.setP2(p2);
        objFo.setP3(p3);
        objFo.setP4(p4);
        objFo.setP5(p5);
        
        
            
        // ESTADO
        String estadoSeleccionadoStr = (String) cmbEstado.getSelectedItem();
        clsEFormularioAdopcion.Estado estadoSeleccionado = null;

        switch (estadoSeleccionadoStr) {
            case "aprobado" -> estadoSeleccionado = clsEFormularioAdopcion.Estado.aprobado;
            case "pendiente" -> estadoSeleccionado = clsEFormularioAdopcion.Estado.pendiente;
            case "rechazado" -> estadoSeleccionado = clsEFormularioAdopcion.Estado.rechazado;
            default -> {
            }
        }
        objFo.setEstado(estadoSeleccionado);
        //Evidencia
        String nombreEvidencia = cmbEvidencia.getSelectedItem().toString();
        int idEvidencia = obteneridEvidencia(nombreEvidencia);
        objEVI.setIdevidencia(idEvidencia);
        //Id Adaptane
        ObtenerIdAdoptante();
        objAdop.setIdAdoptante(idadoptante);
        
        
        //Dni Ingresante
        String dni = Login.dniIngresante;
        
        String nombre = objNFo.obtenerNombre(dni);
        objFo.setNombre(nombre);
        
        
        Login.dniIngresante = "";
       

   
      

        if(objNFo.mtdGuardarFormulario(objFo,objAdop, objEVI)== true){
            JOptionPane.showMessageDialog(null,"GUARDADO");
            btnGuardar.setEnabled(false);
        }else {
            JOptionPane.showMessageDialog(null,"error");

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    private void cargarDatosComboBox() {
        Connection con;
        Conexion cn = new Conexion();
        PreparedStatement ps;
        ResultSet rs;

        try {
            // Establecer conexión con la base de datos
            con = (Connection) cn.getConnection(); // Reemplaza "TuClaseDondeEstablecesConexion" con la clase adecuada para obtener la conexión

            // Consulta SQL para obtener los datos de la tabla CARGO
            String sql = "SELECT nombre FROM evidencia";

            // Preparar la consulta
            ps = con.prepareStatement(sql);

            // Ejecutar la consulta
            rs = ps.executeQuery();

            // Limpiar el combo box antes de agregar nuevos elementos
            cmbEvidencia.removeAllItems();

            // Agregar los elementos del ResultSet al combo box
            while (rs.next()) {
                String nombreevidencia = rs.getString("nombre");
                cmbEvidencia.addItem(nombreevidencia);
            }            
        }catch (SQLException e) {
            System.out.println("Error: " + e.toString());
        } 
    }
    
    private int obteneridEvidencia(String nombreevidencia) {
        int idEvidencia = 0;
        Connection con;
        Conexion cn = new Conexion();
        PreparedStatement ps;
        ResultSet rs;

        try {
            // Establecer conexión con la base de datos
            con = (Connection) cn.getConnection(); 

            // Consulta SQL para obtener el ID del cargo
            String sql = "SELECT idEvidencia FROM evidencia WHERE nombre = ?";

            // Preparar la consulta
            ps = con.prepareStatement(sql);
            ps.setString(1, nombreevidencia);

            // Ejecutar la consulta
            rs = ps.executeQuery();

            // Obtener el ID del cargo
            if (rs.next()) {
                idEvidencia = rs.getInt("idEvidencia");
            }

        }catch (SQLException e) {
            System.out.println("Error: " + e.toString());
        }  
        return idEvidencia;
    }
    
    private void mostrarFechaActual() {
        // Obtener la fecha actual
        LocalDate fechaActual = LocalDate.now();

        String fechaTexto = fechaActual.toString();

        txtFecha.setText(fechaTexto);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbEvidencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPregunta1;
    private javax.swing.JTextField txtPregunta2;
    private javax.swing.JTextField txtPregunta3;
    private javax.swing.JTextField txtPregunta4;
    private javax.swing.JTextField txtPregunta5;
    // End of variables declaration//GEN-END:variables
}
